(function(g){var window=this;'use strict';var nOa=function(a,b){a.Na("onAutonavCoundownStarted",b)},w5=function(a,b,c){var d=b.ib();
g.M(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Se(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.uH&&(b.lengthText?(f=b.lengthText||null,h=b.gy||null):b.lengthSeconds&&(f=g.wM(b.lengthSeconds),h=g.wM(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.xN(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.uH?b.isLivePlayback:null,n=b instanceof g.uH?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Rq||g.hJ("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.Um(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Dt};b instanceof g.yN&&(d.playlist_length=b.length);a.update(d)},x5=function(a){var b=a.T(),c=b.l;
g.V.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",Ea:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],ra:"{{duration}}"},{D:"div",Ea:["ytp-autonav-live-stamp"],ra:"Live"},{D:"div",
Ea:["ytp-autonav-upcoming-stamp"],ra:"Upcoming"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",ra:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Ea:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ra:"{{title}}"},{D:"div",Ea:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ra:"{{author}}"},{D:"div",Ea:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ra:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.i=c;this.Pa("click",this.onClick);this.Pa("keypress",this.l)},z5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;b=a.T();var d=b.l;this.G=a;this.suggestion=null;this.i=new g.V({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ra:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:d?b.I:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],ra:"{{duration}}"},{D:"div",Ea:["ytp-autonav-live-stamp"],ra:"Live"},{D:"div",Ea:["ytp-autonav-upcoming-stamp"],ra:"Upcoming"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",
ra:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ra:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ra:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ra:"{{author_and_views}}"}]}]}]});g.F(this,this.i);this.i.Ba(this.element);d||this.N(this.i.Ca("ytp-autonav-endscreen-link-container"),"click",this.gG);this.G.Zb(this.element,this,115127);this.G.Zb(this.i.Ca("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay"});
g.F(this,this.overlay);this.overlay.Ba(this.element);this.u=new g.V({D:"div",K:"ytp-autonav-endscreen-button-container"});g.F(this,this.u);this.u.Ba(this.element);this.cancelButton=new g.V({D:"button",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Cancel autoplay"},ra:"Cancel"});g.F(this,this.cancelButton);this.cancelButton.Ba(this.u.element);this.cancelButton.Pa("click",this.lO,this);this.G.Zb(this.cancelButton.element,this,115129);this.playButton=
new g.V({D:"a",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},ra:"Play now"});g.F(this,this.playButton);this.playButton.Ba(this.u.element);this.playButton.Pa("click",this.gG,this);this.G.Zb(this.playButton.element,this,115130);this.B=new g.J(function(){y5(c)},500);
g.F(this,this.B);this.fG();this.N(a,"autonavvisibility",this.fG)},C5=function(a){var b=a.G.bj(!0,a.G.isFullscreen());
g.M(a.element,"ytp-autonav-endscreen-small-mode",a.hf(b));g.M(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.Ez);g.M(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.Od());g.M(a.G.getRootNode(),"countdown-running",a.Ch());g.M(a.element,"ytp-player-content",a.G.Od());g.Bl(a.overlay.element,{width:b.width+"px"});if(!a.Ch()){a.G.Od()?A5(a,Math.round(B5(a)/1E3)):A5(a);b=!!a.suggestion&&!!a.suggestion.Dt;var c=a.G.Od()||!b;g.M(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.M(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.AL(a.u,a.G.Od())}},y5=function(a){var b=B5(a),c=Math,d=c.min;
var e=a.l?Date.now()-a.l:0;c=d.call(c,e,b);A5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ch()?a.select(!0):a.Ch()&&a.B.start()},B5=function(a){var b=a.G.gp();
return 0<=b?b:g.T(a.G.T().experiments,"autoplay_time")||1E4},A5=function(a,b){b=void 0===b?-1:b;
a=a.i.Ca("ytp-autonav-endscreen-upnext-header");g.rg(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(/\$SECONDS/gi)[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.qg("Up next in $SECONDS".slice(0,d)));var e=g.pg("span");g.Kq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.wg(e,b);a.appendChild(e);a.appendChild(g.qg("Up next in $SECONDS".slice(d+c.length)));return}}g.wg(a,"Up next")},D5=function(a,b){g.V.call(this,{D:"div",
Ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},F5=function(a){g.V.call(this,{D:"div",
Ea:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",ra:"Up Next"},{D:"span",K:"ytp-upnext-title",ra:"{{title}}"},{D:"span",K:"ytp-upnext-author",ra:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
ra:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.C=this.Ca("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.J(this.Vw,5E3,this);this.l=0;var b=this.Ca("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",Ea:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ra:"Cancel"});g.F(this,this.cancelButton);this.cancelButton.Pa("click",this.mO,this);this.cancelButton.Ba(b);this.cancelButton&&this.api.Zb(this.cancelButton.element,
this,115129);g.F(this,this.B);this.api.Zb(this.element,this,18788);b=this.Ca("ytp-upnext-autoplay-icon");this.N(b,"click",this.nO);this.api.Zb(b,this,115130);this.hG();this.N(a,"autonavvisibility",this.hG);this.N(a,"mdxnowautoplaying",this.eT);this.N(a,"mdxautoplaycanceled",this.fT);this.N(a,"mdxautoplayupnext",this.vM);E5(this)&&(a=(a=g.oN(this.api.sb()))?a.iQ():null)&&this.vM(a);g.M(this.element,"ytp-upnext-mobile",this.api.T().i)},E5=function(a){return 3===a.api.getPresentingPlayerType()},oOa=
function(a,b){return b?b:0<=a.api.gp()?a.api.gp():g.T(a.api.T().experiments,"autoplay_time")||1E4},G5=function(a,b){b=oOa(a,b);
var c=Math,d=c.min;var e=(0,g.O)()-a.l;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.C.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ch()&&!E5(a)?a.select(!0):a.Ch()&&a.i.start()},H5=function(a){D5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.V({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",Ea:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ra:"More videos"}]});this.J=new g.V({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.I=!1;this.l=new z5(this.player);g.F(this,this.l);this.l.Ba(this.element);a.getVideoData().dc?this.i=this.l:(this.i=new F5(a),g.sN(this.player,this.i.element,4),g.F(this,this.i));this.overlay=
new g.V({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.F(this,this.overlay);this.overlay.Ba(this.element);this.B=new g.vN(this);g.F(this,this.B);g.F(this,this.table);this.table.Ba(this.element);this.table.show();g.F(this,this.J);this.J.Ba(this.table.element);this.hide()},pOa=function(a,b){return g.Re(b.suggestions,function(c){c=g.YP(a.player.T(),c);
g.F(a,c);return c})},I5=function(a){var b=a.Od();
b!==a.C&&(a.C=b,a.player.X("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},J5=function(a){D5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",ra:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.F(this,this.i);this.i.Ba(this.element);var b=a.getVideoData();this.subscribeButton=new g.LO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Nh,b.subscribed,"trailer-endscreen",null,null,a);g.F(this,this.subscribeButton);this.subscribeButton.Ba(this.i.Ca("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.Ma);this.Ma();this.hide()},K5=function(a){var b=a.T(),c=g.bj||g.Vk?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Ea:e,U:{href:"{{url}}",target:d?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",ra:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
ra:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ra:"Live"},{D:"span",K:"ytp-videowall-still-info-duration",ra:"{{duration}}"}]}]}]},{D:"span",Ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",ra:"{{playlist_length}}"},")"]}]},{D:"span",Ea:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{D:"span",
K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",ra:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.vN(this);g.F(this,this.i);this.Pa("click",this.onClick);this.Pa("keypress",this.u);this.i.N(a,"videodatachange",this.ob);a.Jg(this.element,this);this.ob()},L5=function(a){D5.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.vN(this);g.F(this,this.l);this.I=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.F(this,this.I);var c=new g.V({D:"button",Ea:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},S:[g.FL()]});g.F(this,c);c.Ba(this.element);c.Pa("click",this.rO,this);this.table=new g.xL({D:"div",K:"ytp-endscreen-content"});g.F(this,this.table);this.table.Ba(this.element);c=new g.V({D:"button",Ea:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},S:[g.GL()]});g.F(this,c);c.Ba(this.element);c.Pa("click",this.qO,this);a.getVideoData().dc?this.i=new z5(a,!0):this.i=new F5(a);
g.F(this,this.i);g.sN(this.player,this.i.element,4);this.hide()},M5=function(a){return g.tN(a.player)&&a.Ct()&&!a.B},qOa=function(a,b){return g.Re(b.suggestions,function(c){c=g.YP(a.G.T(),c);
g.F(a,c);return c})},N5=function(a){var b=a.Od();
b!==a.J&&(a.J=b,a.player.X("autonavvisibility"))},O5=function(a){g.EN.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.vN(this);g.F(this,this.listeners);this.env=a.T();rOa(a)?(this.u=!0,sOa(this),this.i?this.endScreen=new H5(a):this.endScreen=new L5(this.player)):this.env.Kc?this.endScreen=new J5(this.player):this.endScreen=new D5(this.player);g.F(this,this.endScreen);g.sN(this.player,this.endScreen.element,4);tOa(this);this.listeners.N(a,"videodatachange",this.ob,this);this.listeners.N(a,g.Rz("endscreen"),function(c){b.Bd(c)});
this.listeners.N(a,g.Sz("endscreen"),function(c){b.lf(c)})},sOa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Eh&&a.l===b.dc)return!1;a.i=b.Eh;a.l=b.dc;return!0},rOa=function(a){a=a.T();
return a.wb&&!a.Kc},tOa=function(a){a.player.nf("endscreen");
var b=a.player.getVideoData();b=new g.Oz(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Oz(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Hd([b,c])};
g.lN.prototype.gp=g.ca(2,function(){return this.app.gp()});
g.bY.prototype.gp=g.ca(1,function(){return this.getVideoData().oI});
g.v(x5,g.V);x5.prototype.select=function(){(this.G.Ej(this.suggestion.ib().videoId,this.suggestion.Sd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.ZB||void 0)||this.G.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.G.Hb(this.element)};
x5.prototype.onClick=function(a){g.cO(a,this.G,this.i,this.suggestion.Sd||void 0)&&this.select()};
x5.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.gu(a)||(this.select(),g.fu(a))}};g.v(z5,g.V);g.k=z5.prototype;g.k.nt=function(a){this.suggestion!==a&&(this.suggestion=a,w5(this.i,a),this.playButton.Sa("url",this.suggestion.Um()),C5(this))};
g.k.Ch=function(){return 0<this.l};
g.k.ys=function(){this.Ch()||(this.l=Date.now(),y5(this),nOa(this.G,B5(this)),g.M(this.G.getRootNode(),"countdown-running",this.Ch()))};
g.k.Qp=function(){this.em();y5(this);var a=this.i.Ca("ytp-autonav-endscreen-upnext-header");a&&g.wg(a,"Up next")};
g.k.em=function(){this.Ch()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.em()};
g.k.gG=function(a){g.cO(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.Hb(this.playButton.element):a.currentTarget===this.i.Ca("ytp-autonav-endscreen-link-container")&&(a=this.i.Ca("ytp-autonav-endscreen-link-container"),this.G.kb(a,!0),this.G.Hb(a)),this.select())};
g.k.lO=function(){this.G.Hb(this.cancelButton.element);g.nN(this.G,!0)};
g.k.fG=function(){var a=this.G.Od();this.C&&this.xb!==a&&g.AL(this,a);C5(this);this.G.kb(this.element,a);this.G.kb(this.cancelButton.element,a);this.G.kb(this.i.Ca("ytp-autonav-endscreen-link-container"),a);this.G.kb(this.playButton.element,a)};
g.k.hf=function(a){return 400>a.width||459>a.height};g.v(D5,g.V);g.k=D5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Ct=function(){return!1};
g.k.Od=function(){return!1};
g.k.rJ=function(){return!1};g.v(F5,g.V);g.k=F5.prototype;g.k.Vw=function(){this.notification&&(this.B.stop(),this.lc(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.nt=function(a){this.suggestion=a;w5(this,a,"hqdefault.jpg")};
g.k.hG=function(){g.AL(this,this.api.Od());this.api.kb(this.element,this.api.Od());this.api.kb(this.Ca("ytp-upnext-autoplay-icon"),this.api.Od());this.cancelButton&&this.api.kb(this.cancelButton.element,this.api.Od())};
g.k.pT=function(){window.focus();this.Vw()};
g.k.ys=function(a){var b=this;this.Ch()||(g.Ku("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.O)(),this.i=new g.J(function(){G5(b,a)},25),G5(this,a),nOa(this.api,oOa(this,a)));
g.Nq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Ch=function(){return!!this.i};
g.k.Qp=function(){this.em();this.l=(0,g.O)();G5(this);g.K(this.element,"ytp-upnext-autoplay-paused")};
g.k.em=function(){this.Ch()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.S(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.ib(),this.Vw(),this.notification=new Notification("Up Next",{body:b.title,icon:b.Se()}),this.u=this.N(this.notification,"click",this.pT),this.B.start())}this.em();this.api.nextVideo(!1,a)};
g.k.nO=function(a){!g.vg(this.cancelButton.element,g.bu(a))&&g.cO(a,this.api)&&(this.api.Od()&&this.api.Hb(this.Ca("ytp-upnext-autoplay-icon")),this.select())};
g.k.mO=function(){this.api.Od()&&this.cancelButton&&this.api.Hb(this.cancelButton.element);g.nN(this.api,!0)};
g.k.eT=function(a){E5(this);this.show();this.ys(a)};
g.k.vM=function(a){E5(this);this.suggestion&&this.suggestion.ib().videoId===a.ib().videoId||this.nt(a)};
g.k.fT=function(){E5(this);this.em();this.hide()};
g.k.xa=function(){this.em();this.Vw();g.V.prototype.xa.call(this)};g.v(H5,D5);g.k=H5.prototype;g.k.create=function(){D5.prototype.create.call(this);this.B.N(this.player,"appresize",this.kt);this.B.N(this.player,"onVideoAreaChange",this.kt);this.B.N(this.player,"videodatachange",this.ob);this.B.N(this.player,"autonavchange",this.iG);this.B.N(this.player,"autonavcancel",this.oO);this.ob()};
g.k.show=function(){D5.prototype.show.call(this);(this.I||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.nN(this.player,!1);g.tN(this.player)&&this.Ct()&&!this.u?(I5(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.ys():3===this.videoData.autonavState&&this.i.Qp()):(g.nN(this.player,!0),I5(this));this.kt()};
g.k.hide=function(){D5.prototype.hide.call(this);this.i.Qp();I5(this)};
g.k.kt=function(){var a=this.player.bj(!0,this.player.isFullscreen());I5(this);C5(this.l);g.M(this.element,"ytp-autonav-cancelled-small-mode",this.hf(a));g.M(this.element,"ytp-autonav-cancelled-tiny-mode",this.Wx(a));g.M(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Bl(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.q(b.value);b=c.next().value;c=c.next().value;g.M(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.ob=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=pOa(this,a))&&this.suggestions.length)for(this.i.nt(this.suggestions[0]),this.i!==this.l&&this.l.nt(this.suggestions[0]),a=0;a<uOa.length;++a){var b=uOa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new x5(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,w5(c,b));g.F(this,this.videos[a]);this.videos[a].Ba(this.J.element)}}this.kt()}};
g.k.iG=function(a){1===a?(this.I=!1,this.u=this.videoData.clientPlaybackNonce,this.i.em(),this.xb&&this.kt()):(this.I=!0,this.Od()&&(2===a?this.i.ys():3===a&&this.i.Qp()))};
g.k.oO=function(a){a?this.iG(1):(this.u=null,this.I=!1)};
g.k.Ct=function(){return 1!==this.videoData.autonavState};
g.k.hf=function(a){return(910>a.width||459>a.height)&&!this.Wx(a)&&!(400>=a.width||360>=a.height)};
g.k.Wx=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Od=function(){return this.xb&&g.tN(this.player)&&this.Ct()&&!this.u};
var uOa=[1,3,2,4];g.v(J5,D5);J5.prototype.Ma=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.og,author:a.author});this.subscribeButton.channelId=a.Nh;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.v(K5,g.V);K5.prototype.select=function(){(this.api.Ej(this.suggestion.ib().videoId,this.suggestion.Sd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.ZB||void 0)||this.api.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Hb(this.element)};
K5.prototype.onClick=function(a){g.cO(a,this.api,this.l,this.suggestion.Sd||void 0)&&this.select()};
K5.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.gu(a)||(this.select(),g.fu(a))}};
K5.prototype.ob=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.v(L5,D5);g.k=L5.prototype;g.k.create=function(){D5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=qOa(this,a),this.videoData=a);this.Qk();this.l.N(this.player,"appresize",this.Qk);this.l.N(this.player,"onVideoAreaChange",this.Qk);this.l.N(this.player,"videodatachange",this.ob);this.l.N(this.player,"autonavchange",this.IA);this.l.N(this.player,"autonavcancel",this.pO);a=this.videoData.autonavState;a!==this.L&&this.IA(a);this.l.N(this.element,"transitionend",this.HU)};
g.k.destroy=function(){g.xx(this.l);g.jf(this.stills);this.stills=[];this.suggestions=null;D5.prototype.destroy.call(this);g.Nq(this.element,"ytp-show-tiles");this.I.stop();this.L=this.videoData.autonavState};
g.k.Ct=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){D5.prototype.show.call(this);g.Nq(this.element,"ytp-show-tiles");this.player.T().i?g.Gq(this.I):this.I.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.nN(this.player,!1);M5(this)?(N5(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.ys():3===this.videoData.autonavState&&this.i.Qp()):(g.nN(this.player,!0),N5(this))};
g.k.hide=function(){D5.prototype.hide.call(this);this.i.Qp();N5(this)};
g.k.HU=function(a){g.bu(a)===this.element&&this.Qk()};
g.k.Qk=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=this.G.bj(!0,this.G.isFullscreen()),b=g.iN(this.G);b&&(b=b.Je()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,u=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Pl(a,m,n);g.Bl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.nt(this.suggestions[0]);this.i instanceof z5&&C5(this.i);g.M(this.element,"ytp-endscreen-takeover",M5(this));N5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?r=
1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.Of(p+this.u,l),0!==r){t=this.stills[c];t||(t=new K5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-u-4,B=Math.floor(m*(f+r)/b)-x-4;g.Il(t.element,x,u);g.Pl(t.element,B,y);g.Bl(t.element,"transitionDelay",(h+f)/20+"s");g.M(t.element,"ytp-videowall-still-mini",1===r);g.M(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),u=g.Lq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",w5(r,p,u),g.PF(t)&&(t=p.Um(),t=g.ui(t,g.HO("emb_rel_end")),r.Sa("url",t)),(p=(p=p.Sd)&&p.itct)&&r.api.cm(r.element,p));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.tg(e.element),g.ff(e);this.stills.length=c}};
g.k.ob=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=qOa(this,a),this.videoData=a,this.Qk())};
g.k.qO=function(){this.u+=this.stills.length;this.Qk()};
g.k.rO=function(){this.u-=this.stills.length;this.Qk()};
g.k.rJ=function(){return this.i.Ch()};
g.k.IA=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.em(),this.xb&&this.Qk()):(this.C=!0,this.xb&&M5(this)&&(2===a?this.i.ys():3===a&&this.i.Qp()))};
g.k.pO=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.kb(this.stills[a].element,!0);this.IA(1)}else this.B=null,this.C=!1;this.Qk()};
g.k.Od=function(){return this.xb&&M5(this)};g.v(O5,g.EN);g.k=O5.prototype;g.k.fq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!rOa(this.player)||b;var c=a.ze||g.$F(a.B),d=this.player.du();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Od=function(){return this.endScreen.Od()};
g.k.UQ=function(){return this.Od()?this.endScreen.rJ():!1};
g.k.xa=function(){this.player.nf("endscreen");g.EN.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.dH;if(b&&b.videoId){var c=this.player.sb().td.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.HF?a=!1:(this.player.Ej(b.videoId,void 0,void 0,!0,!0,b),c&&c.oy("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.EN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.EN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Bd=function(a){this.fq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.lf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.ob=function(){tOa(this);this.u&&sOa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new H5(this.player):this.endScreen=new L5(this.player),g.F(this,this.endScreen),g.sN(this.player,this.endScreen.element,4))};g.PN.endscreen=O5;})(_yt_player);
